# -*- coding: utf-8 -*-
"""DataCleaning 11:11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wQVv9CXJ1mDjOcXGC0-t_c9n_KpTCLe
"""

import pandas as pd

df = pd.read_csv('StudentPerformanceFactors.csv')
df.head()

df.shape
df.columns

#creating a df copy -> df1
df1 = df.copy()

df1.head(10)

df1.isnull().sum()

#Dropping all missing values from 'Distance From Home'
df1.dropna(subset=['Distance_from_Home'],inplace=True)

df1.isnull().sum()

df2= df1[['Distance_from_Home','Exam_Score','Hours_Studied','Sleep_Hours']].copy()

df_hs = df2[df2['Exam_Score']>80]
df_hs.head(50)

#df2.groupby('Exam_Score').mean()
pd.set_option('display.max_rows', None)     # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)        # Ensure full width is shown
pd.set_option('display.max_colwidth', None) # Ensure columns are fully visible
df_grouped = df2.groupby(['Exam_Score','Distance_from_Home']).mean(numeric_only=True)
df_grouped.head(150)

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

plt.title('Distance From Home  vs. Average Exam Score')
plt.xlabel('Distance_from_Home')
plt.ylabel('Exam_Score')
ax=df1['Exam_Score'].groupby(df1['Distance_from_Home']).mean()
ax.plot(kind='bar', color=sns.color_palette('Set3'))